//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectVW
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TaskCount { get; set; }
        public Nullable<int> CompletedTask { get; set; }
    }
}
